### ISSUE TITLE
Gitlab ci configuration

### ISSUE THREAD

**Issue by arist0v** [charliermarsh/ruff#2454]
Hello, i try settings up ruff for Gitlab Ci code quality, i checked up lot of google result, but still can'T figure out how to make it work

my gitlab-ci.yml:
```
stages:
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

Testing:
  stage: test

  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
    - if: "$CI_COMMIT_TAG =~ /^v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-alpha\\d*|-debug\\d*|-beta\\d*|-rc\\d*|)$/"

  image: "python:3.10"

  before_script:
    - 'pip3 install pytest pytest-asyncio pytest-automock pytest-cov pytest-html-reporter ruff junit2html'

  script:
    - pytest -m GCI -rap --junitxml=gci_test_report.xml
    - ruff ./ --format gitlab > gl-code-quality-report.json


  artifacts:
    name: "${CI_PROJECT_NAME}_tests_reports"
    when: always
    reports:
      codequality: gl-code-quality-report.json
      junit: gci_test_report.xml
    expire_in: never

```

the result:
![image](https://user-images.githubusercontent.com/6615040/216147329-7e435d61-6a05-45d6-8316-3da06c224f14.png)

any tips or information on how i could make it work (also a section in the documentation for github/gitlab integration could be really nice)

**Comment by charliermarsh** [comment]
I've never used Gitlab, but there might be some helpful comments in the original PR? See: #1424.

@saadmk11 may be able to answer a question about it too, if he's available.

**Comment by arist0v** [comment]
Yeah i already tested that without success :(

Le mer. 1 févr. 2023, 16 h 09, Charlie Marsh ***@***.***> a
écrit :

**Comment by saadmk11** [comment]
When I implemented this, I used this config to test it on GitLab CI:

```yaml
include:
  - template: Code-Quality.gitlab-ci.yml


code_quality:
  image: python:3.10-slim
  allow_failure: false
  script:
    - pip install ruff
    - ruff . --format gitlab > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
```

**Comment by arist0v** [comment]
Is it On pipeline or on autodevops?

Le mer. 1 févr. 2023, 16 h 14, Maksudul Haque ***@***.***> a
écrit :

**Comment by arist0v** [comment]
i copy/pasted the @saadmk11 code example, 

i tested with and without the include

and i still have the same error message (gitlab 14)

**Comment by arist0v** [comment]
there is the code i tested

```
include:
  - template: Code-Quality.gitlab-ci.yml


code_quality:
  image: andrejreznik/python-gdal:py3.10.0-gdal3.2.3
  allow_failure: false
  script:
    - pip install ruff
    - ruff . --format gitlab > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
```

**Comment by arist0v** [comment]
so i don'T know why, after few try and stop it's now working.

**Comment by charliermarsh** [comment]
Glad it's working! Sorry I couldn't be more helpful!

**Comment by arist0v** [comment]
no worry, my ci is simple but complex, it's only an include with override. so we create standard ci pipeline for all project

**Comment by arist0v** [comment]
so, new branch, new merge request, same issue, so back to the beginning

**Comment by saadmk11** [comment]
You can checkout the troubleshooting section of GitLab Code Quality Docs: https://docs.gitlab.com/ee/ci/testing/code_quality.html#troubleshooting

**Comment by arist0v** [comment]
Ok so look like it'S working now, 

there is a small recap in case you would like to documente the step in the official documentation:
```
# could be any name if you don't use the template (the template is not required for the process to work)
code_quality:
  stage: test
 # not sure if you could use a different stage

  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push'" 
    # THIS TRIGGER IS REQUIRED IF YOU WANT THE PROCESS TO WORK

    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'" 
    # I want it to run also when i create a merge_request(or update)

  image: "python:3.10"

  before_script:
    - 'pip3 install ruff'
    # don't forger to install ruff 

  script:
    - ruff ./ --format gitlab > gl-code-quality-report.json
    # redirect output to a json file(could be any name)


  artifacts:
    name: "${CI_PROJECT_NAME}_code_quality" 
    #artifact could have any name
    when: always
    # i want the artifact to be created even if test failed
    reports:
      # the artifact is a reports object
      codequality: gl-code-quality-report.json
      # artifact is a codequality artifact this must be your json name (any name)
      
    expire_in: never

```

**Comment by charliermarsh** [comment]
Awesome, thanks for following up!

**Comment by arist0v** [comment]
i still have a fix to do, the pipeline run on main after i merged, i want to prevent that to happend, i update my post in few min with the final answer
